### ISSUE TITLE
Add ioPay wallet

### ISSUE THREAD

**Issue by chen-yijiang** [anza-xyz/wallet-adapter#1019]
Hi, Team Solana-Labs,

This PR [#1017](https://github.com/anza-xyz/wallet-adapter/pull/1017) adds [ioPay](https://iopay.me/) wallet to the list of supported wallets to make it easier for our users to connect to wallet-adapter dapps.

Please let me know if anything needs to be added or changed to satisfy your requirements.

Cheers,
ioPay Wallet team

@ssamkkim

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@chen-yijiang

**Comment by jordaaash** [comment]
We aren't accepting new adapters for injected wallets. See the [guide for wallets](https://github.com/anza-xyz/wallet-adapter/blob/master/WALLET.md). You'll want to implement the Wallet Standard in your wallet and register it as a Standard Wallet. When you do, it will be detected automatically by Solana apps that use Wallet Adapter.
