### ISSUE TITLE
Upgrade @solana/web3.js to V2

### ISSUE THREAD

**Issue by xcaptain** [anza-xyz/wallet-adapter#1027]
`@solana/web3.js@v2.0.0-rc1` has been released for about 2 months, any plan to upgrade to this version?

**Comment by xcaptain** [comment]
I made a simple demo using the new `web3.js`, code is at: https://github.com/xcaptain/solana-wallet-demo

frame used is svelte, if you use react you can try https://github.com/solana-labs/solana-web3.js/tree/master/examples/react-app

This wallet-adapter repository is outdated, don't use in new projects

**Comment by steveluscher** [comment]
> This wallet-adapter repository is outdated, don't use in new projects

Correct. This wallet adapter is superseded by https://github.com/solana-labs/solana-web3.js/tree/master/packages/react and https://github.com/wallet-standard/wallet-standard/tree/master/packages/react/core where `@solana/web3.js@2.0` is concerned.
