### ISSUE TITLE
Browser Wallet Interface

### ISSUE THREAD

**Issue by pynixwang** [anza-xyz/wallet-adapter#1038]
we need something like https://eips.ethereum.org/EIPS/eip-6963

make an interface and let wallet implement it.

not endless wallet adapter.

**Comment by mcintyre94** [comment]
We already have this with [wallet-standard](https://github.com/wallet-standard/wallet-standard). All wallet-standard wallets are automatically detected and included by all apps using wallet-adapter. Apps don't need to include adapters any more. Also see https://github.com/anza-xyz/wallet-adapter/blob/master/APP.md
