### ISSUE TITLE
signMessage method from useWallet raised typescript error

### ISSUE THREAD

**Issue by MrPhyaeSoneThwim** [anza-xyz/wallet-adapter#124]
Can you please help me how to solve this typescript error for signMethod shown in the following picture?

![error](https://user-images.githubusercontent.com/83585609/137321397-7a2e2470-75d6-4cb4-9bf9-8fb0f4e2c264.png)

**Comment by silvestrevivo** [comment]
The type for that functions should be as follows:

`signMessage: MessageSignerWalletAdapterProps['signMessage'] | undefined;`
