### ISSUE TITLE
Decrease NPM package size

### ISSUE THREAD

**Issue by chancity** [anza-xyz/wallet-adapter#131]
**Is your feature request related to a problem? Please describe.**
The NPM package size is extremely large and impacts frontend performance. 

**Describe the solution you'd like**
A smaller NPM package

**Additional context**
https://bundlephobia.com/package/@solana/wallet-adapter-wallets@0.10.2

**Comment by jordansexton** [comment]
You're looking at the size of the wallets package, which includes all wallets and their dependencies. Dapps only add a few of these practice, and the package supports tree shaking.

Have you tried using this in an application and seeing how large it actually is?

**Comment by jordansexton** [comment]
Related: https://github.com/solana-labs/wallet-adapter/issues/69
