### ISSUE TITLE
Module not found: Can't resolve '@particle-network/auth'

### ISSUE THREAD

**Issue by sotatek-dungduong2** [anza-xyz/wallet-adapter#880]
**Describe the bug**
- error - ./node_modules/@particle-network/solana-wallet/es/index.js:118:0
Module not found: Can't resolve '@particle-network/auth'

Import trace for requested module:
./node_modules/@solana/wallet-adapter-particle/lib/esm/adapter.js
./node_modules/@solana/wallet-adapter-particle/lib/esm/index.js
./node_modules/@solana/wallet-adapter-wallets/lib/esm/index.js
**To Reproduce**
Yarn install package solana -> run code and get error.
**Expected behavior**
Not error.

Current version in package.json:
      @solana/spl-token": "^0.3.9",
    "@solana/spl-token-registry": "^0.2.4574",
    "@solana/wallet-adapter-react": "^0.15.35",
    "@solana/wallet-adapter-react-ui": "^0.9.34",
    "@solana/wallet-adapter-wallets": "^0.19.24",
    "@solana/web3.js": "^1.87.6",

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macOS
 - Browser [e.g. chrome, safari]: Chrome

**Comment by avoc-ado** [comment]
I also have the issue with @solana/wallet-adapter-wallets@0.19.25 when running `next dev`. There are no compile errors

**Comment by LanPRD** [comment]
I was using vite@4.3.5. Some dependencies in "@particle-network" were not installed... But I have other project with @solana/wallet-adapter-wallets and in this project I never had any problems and in node_modules the dependencies was installed successfully. So I tried updated vite, now vite@5.0.10. The errors had to happen, but now, different...

To solve my issues I needed install `nodePolyfills` and change my `vite.config.ts`.

vite.config.ts
`export default defineConfig({
  optimizeDeps: {
    exclude: ["@particle-network"]
  },
  build: {
    rollupOptions: {
      external: ["@particle-network/auth"]
    }
  },
  define: {
    globalThis: "window"
  },
  resolve: {
    alias: {
      process: "process/browser",
      util: "util"
    }
  },
  plugins: [
    react(),
    svgr({
      include: "**/*.svg?react",
      exclude: "",
      svgrOptions: {
        // svgr options
      }
    }),
    nodePolyfills()
  ]
});`

In my case, I needed to remove this line from my project too:
`window.Buffer = Buffer`

**Comment by tolgaand** [comment]
i'm using next@14.0.4, same issue.

**Comment by lukecaan** [comment]
Anyone know a quick way to get things building locally again? Just go back to an old version of the library before particle-network got added?

**Comment by ez-krk** [comment]
same issue, rolling back to 0.19.24 didn't helped for me.

**Comment by tolgaand** [comment]
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.externals.push("@particle-network/auth");
    }
    return config;
  }
};

module.exports = nextConfig;
```

fixed for me

**Comment by jordaaash** [comment]
Sorry about the workarounds here. I'm pushing to get this fixed.

**Comment by jordaaash** [comment]
This should be fixed via https://github.com/solana-labs/wallet-adapter/pull/891

**Comment by jordaaash** [comment]
Released via https://github.com/solana-labs/wallet-adapter/pull/890.

Please update to the latest version of the `@solana/wallet-adapter-wallets` (`^0.19.26`) which includes an updated package for the Particle adapter, and try to install and build again.

Let me know if it works or doesn't!
