### ISSUE TITLE
Wallet Address Not Auto-Filling After Connection

### ISSUE THREAD

**Issue by M4rlock** [anza-xyz/wallet-adapter#895]
Hi Folks,
I'm reaching out for a bit of help with an issue I've encountered while integrating the Solana wallet adapter into our React application, specifically with Phantom wallet connectivity.

**Issue Description:**

After successfully connecting the Phantom wallet, we anticipate the user's public wallet address to automatically populate a designated input field within our application. Unfortunately, this doesn't seem to be happening, and I'm a bit puzzled as to why.

**Steps to Reproduce:**

Visit our application. --> [React App](https://submit.dedz.xyz/react/)
Initiate the wallet connection by selecting the "Connect Wallet" button.
Choose the Phantom Wallet from the options and authenticate the connection.

**Expected Outcome:**

Post connection, the "Wallet Address" input field should reflect the user's public wallet address, showcasing a seamless integration.
Strangely, if you connect the wallet and refresh the page, it works as it should, but if you do not refresh the page, the problem persists.

![image](https://github.com/anza-xyz/wallet-adapter/assets/122162956/e4f8ac3c-f533-44a2-88e6-2ca20839cdc1)

**Actual Outcome:**
Despite a successful connection, the "Wallet Address" field remains unfilled.

![image](https://github.com/anza-xyz/wallet-adapter/assets/122162956/0cc57f30-b8ed-43aa-b364-a5fb84b00c8e)

You can access the entire code from the link below.
[React Code
](https://codeshare.io/pA0y46)

Technical Details:

- React version: [18.2.0]
- @solana/wallet-adapter-react version: [0.15.35]
- Browser(s): [Chrome, Firefox]
- Wallet Used: Phantom

Request:
I would immensely appreciate any guidance, updates, or suggestions for workarounds you might have to ensure the wallet address populates as expected. 

Thank you very much for your time in advance.

**Comment by jordaaash** [comment]
In your [example code](https://codeshare.io/pA0y46) you are calling the `useWallet()` hook outside of your `WalletProvider`'s context. This won't work. Check your console, there should be a bunch of warnings about this.

**Comment by jordaaash** [comment]
You are also passing `wallets={[new PhantomWalletAdapter()]}` to the `WalletProvider`. Since this will occur on every render, you'll get a new array and a new Phantom adapter. This will also not work. I would recommend looking at the example or other starter projects in the repo, or use https://github.com/solana-labs/dapp-scaffold
