### ISSUE TITLE
Tidus Wallet Support

### ISSUE THREAD

**Issue by michaelessiet** [anza-xyz/wallet-adapter#897]
**Describe the solution you'd like**
Hi, can I make a PR to add [Tidus Wallet](https://tiduswallet.com)? Or is there another way that I can add Tidus Wallet to the list of detected providers without having to open a PR and add Tidus as a package here explicitly? Maybe kinda like EIP6369?

P.S: I noticed that backpack isn't in the wallets directory but is supported

**Comment by jordaaash** [comment]
See https://github.com/anza-xyz/wallet-adapter/blob/master/WALLET.md

The Wallet Standard provides the detection mechanism for wallets.

**Comment by michaelessiet** [comment]
> See https://github.com/anza-xyz/wallet-adapter/blob/master/WALLET.md
> 
> The Wallet Standard provides the detection mechanism for wallets.

Hey, so I keep getting this error from while using the example dapp in `packages/starters/react-ui-starter`

![Screenshot 2024-02-12 at 02 23 23](https://github.com/anza-xyz/wallet-adapter/assets/23281128/c2a62d29-e992-46d5-91d1-761456bddd51)

I implemented everything as mentioned in the markdown file that you sent me. Funny thing is that when I log the particular callback function that is supposedly undefined or not a function, it shows up as a function in the console `s=>register(a)`(minified). Help or a more in-depth guide would be much appreciated.

**Comment by michaelessiet** [comment]
BTW this happens after the `registerWallet` function is called and when the event is dispatched. And yes, detail is also defined and is also a function when I log it.

![Screenshot 2024-02-12 at 02 27 18](https://github.com/anza-xyz/wallet-adapter/assets/23281128/18dbbbfa-bb6e-43f6-9109-79971762900b)

**Comment by michaelessiet** [comment]
@jordaaash
