### ISSUE TITLE
Backpack sign message incorrect format

### ISSUE THREAD

**Issue by valentyn-solana** [anza-xyz/wallet-adapter#898]
When I sign message with backpack adapter I get back the object { signature: Uint8Array }
For all other wallets (tested phantom, solflare) I get signature itself (Uint8Array ) without being wrapped in object

Small issue, but hope it should be same format :)

**Comment by ph101pp** [comment]
we're following this standard here: https://github.com/anza-xyz/wallet-standard/blob/master/packages/wallets/ghost/src/window.ts#L25
