### ISSUE TITLE
auto redirection after Solana Wallet Integration - to https://solanamobile.com/wallets

### ISSUE THREAD

**Issue by LFerronato** [anza-xyz/wallet-adapter#936]
Guys, needing help, this is the first time I'm using the Solana integration and some strange things are happening;

**Describe the bug**
Some of our users have reported that when they attempt to access our dApp, they are being redirected to https://solanamobile.com/wallets. This behavior is unexpected and has not been coded into our dApp by our team.
(video -
https://github.com/anza-xyz/wallet-adapter/assets/43012047/54ae16cf-320a-44a7-9782-73db23e18ff2)

**To Reproduce**
1. Go to https://gray.market
2. just wait (video)

**Expected behavior**
I believe that is very intrusive and affect the dApp's sense of security, a redirect like this.
It's not the kind of thing that a lib should generate as a side effect.
So, the expected behavior It would be if this didn't exist by default

**Smartphone (please complete the following information):**
I'm not sure which devices, there are reports from several users that this is happening.

**Additional context**
I wrote this note: https://github.com/anza-xyz/wallet-adapter/issues/604#issuecomment-2021430962
I have openned a issue here before: https://github.com/solana-labs/solana-web3.js/issues/2378

Dependencies:
```
    "@solana/spl-token": "^0.4.0",
    "@solana/wallet-adapter-react": "^0.15.35",
    "@solana/wallet-adapter-react-ui": "^0.9.34",
    "@solana/wallet-adapter-wallets": "^0.19.25",
    "@solana/web3.js": "^1.89.1",
    "bs58": "^5.0.0",
    "next": "14.0.4",
```

**Comment by LFerronato** [comment]
I'm looking closely at the SolanaProvider code and I see that there are improvements to make. but the point still remains, that redirect is a side effect that is not legal...

```
export const SolanaProvider: FC<SolanaProviderProps> = ({ children }) => {
  const [network, setNetwork] = useState<NetworkState>({
    chainId: '01',
    token: 'SOL',
  })

  const endpoint = 'https://api.metaplex.solana.com/'
  const walletPhantom = useMemo(() => new PhantomWalletAdapter(), [])
  const walletTrust = useMemo(() => new TrustWalletAdapter(), [])
  const walletSolFlare = useMemo(() => new SolflareWalletAdapter(), [])

  const contextValue = useMemo(
    () => ({
      setNetwork,
      network,
    }),
    [network]
  )

  return (
    <ConnectionProvider endpoint={endpoint}>
      <WalletProvider
        localStorageKey="SolanaWallet"
        autoConnect={false}
        wallets={[walletPhantom, walletTrust, walletSolFlare]}
      >
        <WalletModalProvider>
          <WalletConnectionListener>
            <SolanaContext.Provider value={contextValue}>
              {children}
            </SolanaContext.Provider>
          </WalletConnectionListener>
        </WalletModalProvider>
      </WalletProvider>
    </ConnectionProvider>
  )
}

const WalletConnectionListener: FC<{ children: ReactNode }> = ({ children }) => {
  const { wallet, connect, connected, disconnect } = useWallet()
  const { wallet: currentWallet } = useWalletStore()
  const { setWallet, setProvider } = useWalletStore.getState()
  const { connection } = useConnection()
  const { setNetwork, network } = useSolana()
  const endpoint = connection.rpcEndpoint

  function fetchNetwork(endpoint: string) {
    if (endpoint === clusterApiUrl('mainnet-beta')) {
      setNetwork({ chainId: '01', token: 'SOL' })
    } else if (endpoint === clusterApiUrl('devnet')) {
      setNetwork({ chainId: '02', token: 'SOLANA_TEST' })
    }
  }

  useEffect(() => {
    const initiateConnection = async () => {
      if (wallet) {
        try {
          if (connected && currentWallet) return
          await connect()
          console.log('Wallet successfully connected.')
          setWallet(wallet.adapter.publicKey?.toBase58() ?? '')
          setProvider('sol')
          fetchNetwork(endpoint)
          console.log('network:', network)
        } catch (error) {
          console.error('Error connecting wallet:', error)
        }
      }
    }
    initiateConnection()
  }, [wallet?.adapter, connection.rpcEndpoint, connected, connect])

  useEffect(() => {
    const checkLocalStorageKey = setInterval(() => {
      const isSolanaWallet = localStorage.getItem('SolanaWallet')
      if (!isSolanaWallet && connected) {
        console.log('disconnecting wallet...')
        disconnect()
      }
    }, 1000)

    return () => clearInterval(checkLocalStorageKey)
  }, [disconnect, connected])

  return <>{children}</>
}
export const useSolana = () => useContext(SolanaContext)

```

**Comment by steveluscher** [comment]
When on mobile, your code _must not_ attempt to autoconnect to the wallet. If you do, this is what happens:

1. You try to autoconnect
2. The mobile wallet adapter tries to make a connection
3. Because the connection did not originate from a user gesture (eg. a tap on the screen) the browser's popup blocker blocks it.
4. Mobile wallet adapter presumes that there is no installed wallet, and redirects to the wallets landing.

Again: _do not autoconnect or call `connect()` programmatically on mobile_.
