### ISSUE TITLE
Why did many adapters were removed 8 months ago

### ISSUE THREAD

**Issue by kyrkpto** [anza-xyz/wallet-adapter#945]
Many adapters were removed from the project, Backpack, Slope, etc... in the commit comments is saying 
![deprecated-wallet-adapters](https://github.com/anza-xyz/wallet-adapter/assets/166804631/4deefec0-abd5-4a22-96fb-ae90e5ab7a40)

was just removing them, the right way to proceed with it? how can we proceed to integrate them again

thanks, and sorry if i'm not up to date on these changes just want to know the best way to move forward on this.

**Comment by mcintyre94** [comment]
These are either deprecated wallets, or wallets that have implemented the wallet standard and no longer need an adapter. Wallets that implement wallet-standard are available to all apps without their adapter being included in the app.
