### ISSUE TITLE
wallet connet work local good but when i deploy to vercel not work ?

### ISSUE THREAD

**Issue by ArDapps** [anza-xyz/wallet-adapter#951]

**Comment by Andrew-Pynch** [comment]
this is a dogshit issue description, but I have the same problem. Get the prompt to sign in, but a session isn't generated when I come back from phantom prompt to sign in

**Comment by mcintyre94** [comment]
Can you please provide source code and a Vercel link that reproduces this?

**Comment by jordaaash** [comment]
No repro / details.
