### ISSUE TITLE
TypeError: off is not a function

### ISSUE THREAD

**Issue by umaid56** [anza-xyz/wallet-adapter#954]
I get this error whenever I use the Solana wallet adapter package in my Next.js project. Every time I run the project, I encounter this error initially. However, after refreshing the page, the wallet connection works fine, and transitions through Phantom also work well. But whenever I stop and restart the server on localhost, I consistently encounter this error again.

```
Unhandled Runtime Error
TypeError: off is not a function

Call Stack
StandardWalletAdapter.destroy
webpack-internal:/node_modules/@solana/wallet-standard-wallet-adapter-react/node_modules/@solana/wallet-standard-wallet-adapter-base/lib/esm/adapter.js (102:1)
eval
webpack-internal:/node_modules/@solana/wallet-standard-wallet-adapter-react/lib/esm/useStandardWalletAdapters.js (24:14)
Array.forEach
<anonymous>
eval
webpack-internal:/node_modules/@solana/wallet-standard-wallet-adapter-react/lib/esm/useStandardWalletAdapters.js (24:14)

```

**Comment by ronypk999** [comment]
This is also happening with me.. besides another error encounters often with object.setToggle.
These bugs must be solved quickly

**Comment by ronypk999** [comment]
![Uploading Screenshot from 2024-05-04 20-34-13.png…]()

**Comment by mcintyre94** [comment]
Can you provide source code or a link to a hosted example of this please? I don't see this on our hosted example project: https://anza-xyz.github.io/wallet-adapter/example/

**Comment by jordaaash** [comment]
Closing as no repro / stale. Please provide more details.
