### ISSUE TITLE
Sending transaction with devnet connection does not work with Solflare wallet

### ISSUE THREAD

**Issue by ZYJLiu** [anza-xyz/wallet-adapter#957]
**Describe the bug**
Sending a transaction to Solflare wallet does not work with devnet connection.  When a transaction is sent, the connection switches to mainnet which results in an error from Solflare wallet. Both the wallet and frontend connection are set to devnet, and the transaction works as expected when using Phantom wallet.

**To Reproduce**
1. Set connection on both frontend and Solflare to devnet
2. Use `@solana/wallet-adapter-solflare` to connect to Solflare wallet
3. Send a transaction, which results in the "Network Mismatch" error from the wallet.

**Expected behavior**
Successfully send a transaction with devnet connection

**Screenshots**
![CleanShot 2024-05-02 at 15 35 17](https://github.com/anza-xyz/wallet-adapter/assets/75003086/953aa26c-abd6-418c-aab0-2603dc9b7059)

**Desktop:**
 - OS: iOS
 - Browser: Chrome, Brave

**Comment by mcintyre94** [comment]
Please can you provide source code and a link to view your repro of this?

**Comment by mcintyre94** [comment]
Got it thanks, this looks like a Solflare bug, I've reported it to them. It can also be reproduced on https://anza-xyz.github.io/wallet-adapter/example which sends transactions on devnet.
