### ISSUE TITLE
Firebase auth

### ISSUE THREAD

**Issue by agolho** [anza-xyz/wallet-adapter#958]
The signin dynamic function seems like a good place to start but I am at a loss to where to start with firebase authentication with this wallet.

Is there anybody who implemented this solution?

Can we use firebase authentication with message signing so users are logged in to firebase also?

**Comment by mcintyre94** [comment]
Wallet-adapter is not a wallet. You'd need to create a wallet that works with Firebase auth. See https://github.com/anza-xyz/wallet-adapter/blob/master/WALLET.md for information on creating a wallet that is compatible with wallet-adapter.
