### ISSUE TITLE
Where to import useWalletMultiButton in CustomConnectButton

### ISSUE THREAD

**Issue by josephchung796** [anza-xyz/wallet-adapter#964]
I tried to define my custom wallet connect button but it throws an error.
![image](https://github.com/anza-xyz/wallet-adapter/assets/167800418/a57bd71f-bcd7-4e8e-a876-6d5e558a72a7)

![image](https://github.com/anza-xyz/wallet-adapter/assets/167800418/e2caf4e7-bba6-4174-a9cc-68080bbc24d6)

Where should I import that hook from?

**Comment by adkstar** [comment]
> I tried to define my custom wallet connect button but it throws an error. ![image](https://private-user-images.githubusercontent.com/167800418/330759958-a57bd71f-bcd7-4e8e-a876-6d5e558a72a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTM2MDcsIm5iZiI6MTcyMDM5MzMwNywicGF0aCI6Ii8xNjc4MDA0MTgvMzMwNzU5OTU4LWE1N2JkNzFmLWJjZDctNGU4ZS1hODc2LTZkNWU1NThhNzJhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QyMzAxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDlhNzFlNGVlZmE1NGNkOTU2ZjVkZDc0YzZlZjQwMzg1ZjkwMzNmYWZjODM3ZWQ5ZjI0YzBkNDQ0NDNiNGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R9BEQY8beLW4P6LVq_q84xacdQoVr4MqQ7YIm1u9SXU)
> 
> ![image](https://private-user-images.githubusercontent.com/167800418/330760468-e2caf4e7-bba6-4174-a9cc-68080bbc24d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTM2MDcsIm5iZiI6MTcyMDM5MzMwNywicGF0aCI6Ii8xNjc4MDA0MTgvMzMwNzYwNDY4LWUyY2FmNGU3LWJiYTYtNDE3NC1hOWNjLTY4MDgwYmJjMjRkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QyMzAxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzUwYWU3ZjBiODNiZmJhMzQ3Yzk3MGU1NWI0ODdmYTJmMmIyNTRmOGJkYWM3YzEwMzM4NGFhMGMxZDlhMjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y0CPxQiMHxcvg5kCol1Yuphtf7EaZq9u_lrEr28XBLY)
> 
> Where should I import that hook from?

You can import it from  `@solana/wallet-adapter-base-ui` like

`import { useWalletMultiButton } from '@solana/wallet-adapter-base-ui';`
