### ISSUE TITLE
Phantom on mainnet mode successfully signAndSend transactions while app is using a testnet

### ISSUE THREAD

**Issue by phoenixVS** [anza-xyz/wallet-adapter#971]
When Phantom on mainnet mode and app is using test- devnet, you can sign
and send transactions with wallet using signAndSendTransactions and it even returns 
some transaction hash which is not present in solscan

**To Reproduce**
1. Go to https://lab.web3modal.com/library/solana/
2. Disable testnet mode in phantom and connect
3. select test | dev net and run Sign and Send transaction (both V0 and legacy ones)
4. You recieve a signature instead of thowing some error

**Expected behavior**
It should throw some error instead

**Screenshots**
![image](https://github.com/anza-xyz/wallet-adapter/assets/28185581/19d6de4a-fedd-4400-a35b-4563c3eefb34)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Versions:
   "@solana/wallet-adapter-base": "0.9.23",
   "@solana/wallet-adapter-phantom": "0.9.24"
   
  **Additional context**
 (i.e. if you run devnet trx in testnet mode - it gives an error)

**Comment by jordaaash** [comment]
Please report issues with Phantom to Phantom. Also, using an adapter for Phantom generally won't be necessary, since it supports the Wallet Standard. If a transaction hash isn't found in an explorer, make sure you're using the same cluster in the app, wallet settings, and explorer.
