### ISSUE TITLE
sendTransaction doesn't work with String data

### ISSUE THREAD

**Issue by josephchung796** [anza-xyz/wallet-adapter#978]
**Describe the bug**
I wrote a Solana program which takes the String data as an account.
And once I encoded the String data with buffer-layout, and called sendTransaction from useWallet hook, it totally failed with the below error message.
Error: Expected String

**Screenshots**
![image](https://github.com/anza-xyz/wallet-adapter/assets/167800418/580d790f-b6a4-418f-a5b4-488fcd3a2638)

**Desktop (please complete the following information):**
 - OS: Windows, Ubuntu 22.04
 - Browser Chrome, Firefox

**Comment by jordaaash** [comment]
This doesn't look like a Wallet Adapter issue, but even if it is, we can't test it from the provided description. Please provide a link to a repo that reproduces it if you still think it is, and I'll reopen.
