### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by Tarbez** [anza-xyz/wallet-adapter#982]
**Describe the bug**
Using the default components designed by the library, I can't seem to figure a way to fix this unless I do overwrite most of the work and the files, and since am using a the new version of nextjs somehow I'm facing this issue > 

Error: Hydration failed because the initial UI does not match what was rendered on the server.

**To Reproduce**
1. Simply use the library in nextjs 14+
2. the issue for the hydration should appear

**Expected behavior**
It should not be a button that is wrapping the next component cause then you would have 2 buttons  nested. 

**Screenshots**
![Screenshot 2024-06-08 at 00 55 31](https://github.com/anza-xyz/wallet-adapter/assets/33286159/766bd80e-f828-4f7d-ac05-65511b9bb875)

**Comment by jordaaash** [comment]
> dynamic in Next is the best way to resolve this

Yeah, that's right. The state on the client will always be different than the server because the server can't know about the wallets injected into the browser.
