### ISSUE TITLE
Add OKX wallet adapter

### ISSUE THREAD

**Issue by h0lme3** [anza-xyz/wallet-adapter#993]
Hi everybody,

We want to let users connect OKX wallet in our dApp and we are using `@solana/wallet-adapter-wallets` dep which is not listed yet

Can we add okx wallet like okx wallet adapter?

Thanks

**Comment by glitch-txs** [comment]
Any plans on supporting the Wallet Standard?

**Comment by puderty** [comment]
> Hi everybody,
> 
> We want to let users connect OKX wallet in our dApp and we are using `@solana/wallet-adapter-wallets` dep which is not listed yet
> 
> Can we add okx wallet like okx wallet adapter?
> 
> Thanks

which dApp and what platform is it? I think okx wallet already supported wallet adapter

**Comment by h0lme3** [comment]
> which dApp and what platform is it? I think okx wallet already supported wallet adapter

Hmm I believe I am using the latest `@solana/wallet-adapter-wallets` version (`^0.19.32`) and it doesnt include okx wallet adapter I think at the moment.

**Comment by h0lme3** [comment]
> Any plans on supporting the Wallet Standard?

Not now, just wrote for the feature request for now.

**Comment by kAsky53** [comment]
> Any plans on supporting the Wallet Standard?

It already supports wallet standard.
I think it's still useful for installation though.

**Comment by glitch-txs** [comment]
Then why do you need the adapter?

**Comment by kAsky53** [comment]
> Then why do you need the adapter?

If I have not installed OKX wallet, I would still like it to be shown in available wallet list where I can click and install the wallet app.

**Comment by glitch-txs** [comment]
what's your expected behavior when clicked by a user?

**Comment by kAsky53** [comment]
> what's your expected behavior when clicked by a user?

It should redirect to `https://www.okx.com/web3` so that I can install the wallet app.

**Comment by zwergdev** [comment]
Added `packages/wallets/okx/src/adapter.ts` in one of my projects. Everything is ok.

**Comment by kAsky53** [comment]
> you could create a custom adapter and add name, icon and url as config args rather than one for each wallet. I guess it only needs to be filtered by WS and trigger the URL on `connect`

Would you mind sharing code snippet for it?

**Comment by jordaaash** [comment]
Thanks, but we are not accepting new adapters for wallets that can support the Wallet Standard. Since OKX Wallet already does, this is unnecessary.
