### ISSUE TITLE
error ：./scripts/cargo-install-all.sh .

### ISSUE THREAD

**Issue by songqingshududu** [anza-xyz/wallet-adapter#994]
![image](https://github.com/anza-xyz/wallet-adapter/assets/142251921/73fbb73d-78ab-473d-9523-d546b7c2d91c)
When I deploy the node, I execute this command:./scripts/cargo-install-all.sh. This error causes the node to not compile successfully
install solana version：v1.18.15
rust： rustc 1.79.0 (129f3b996 2024-06-10)

**Comment by mcintyre94** [comment]
There's no rust/cargo in this repo so this isn't the right place for this issue. This repo is for the frontend wallet-adapter library.
